In [1]:
import os
import pandas as pd


# 1. Mendapatkan path ke folder Desktop secara otomatis
folder_path = r'C:\protofolio\ecommerce_analytic\data mentah'

# 3. Membaca file menggunakan pandas
df_transactions = pd.read_csv(os.path.join(folder_path, 'transactions.csv')).copy()
df_transactions.head()

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag
0,1,2021-12-27 08:25:15,59540,1630.0,3,0.00,43.74,0,0
1,2,2023-06-06 21:14:26,54871,1901.0,3,0.00,174.78,21,0
2,3,2023-08-31 05:29:54,51818,1884.0,1,0.00,40.61,37,0
3,4,2022-06-26 20:33:46,18164,1114.0,2,0.15,68.76,13,0
4,5,2023-07-26 18:12:35,86915,408.0,1,0.00,14.64,4,0

In [2]:
df_transactions.isnull().sum()

transaction_id          0
timestamp               0
customer_id             0
product_id          10449
quantity                0
discount_applied        0
gross_revenue       10449
campaign_id             0
refund_flag             0
dtype: int64

In [3]:
#df_transactions['refund_flag'].unique()
print(df_transactions['refund_flag'].value_counts())
#gross data minus
jumlah_minus = (df_transactions['gross_revenue'] < 0).sum()
print(f"Ada minus: {jumlah_minus}")

refund_flag
0    100098
1      3029
Name: count, dtype: int64
Ada minus: 2704

In [ ]:
# Melihat sampel data yang gross_revenue-nya < 0
negative_revenue = df_transactions[df_transactions['gross_revenue'] < 0]

# berapa banyak dari data negatif ini yang punya refund_flag == 1
print(negative_revenue['refund_flag'].value_counts())

# gross_revenue negatif yang bukan refund (refund_flag == 0)
data_aneh = df_transactions[(df_transactions['gross_revenue'] < 0) & (df_transactions['refund_flag'] == 0)]

print(f"Jumlah data negatif yang BUKAN refund: {len(data_aneh)}")

refund_flag
1    2704
Name: count, dtype: int64
Jumlah data negatif yang BUKAN refund: 0

In [5]:
import numpy as np

df_transactions_clean = df_transactions.dropna(subset=['product_id', 'gross_revenue'])

# Membuat kolom baru bernama 'net_revenue'
df_transactions_clean['net_revenue'] = np.where(
    df_transactions_clean['refund_flag'] == 1, 
    0, 
    df_transactions_clean['gross_revenue']
)

# hasil
display(df_transactions_clean[['transaction_id', 'gross_revenue', 'refund_flag', 'net_revenue']].head(10))

   transaction_id  gross_revenue  refund_flag  net_revenue
0               1          43.74            0        43.74
1               2         174.78            0       174.78
2               3          40.61            0        40.61
3               4          68.76            0        68.76
4               5          14.64            0        14.64
5               6         169.74            0       169.74
6               7          42.48            0        42.48
7               8          36.95            0        36.95
8               9         125.59            0       125.59
9              10          48.72            0        48.72

In [6]:
df_transactions_clean.dtypes

transaction_id        int64
timestamp               str
customer_id           int64
product_id          float64
quantity              int64
discount_applied    float64
gross_revenue       float64
campaign_id           int64
refund_flag           int64
net_revenue         float64
dtype: object

In [7]:
# 3. create kolom transaction date

df_transactions_clean['timestamp'] = pd.to_datetime(df_transactions_clean['timestamp'])
df_transactions_clean['transaction_date'] = df_transactions_clean['timestamp'].dt.date

#  hasil
#display(df_transactions_clean['transaction_date'])
display(df_transactions_clean.head())

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag,net_revenue,transaction_date
0,1,2021-12-27 08:25:15,59540,1630.0,3,0.00,43.74,0,0,43.74,2021-12-27
1,2,2023-06-06 21:14:26,54871,1901.0,3,0.00,174.78,21,0,174.78,2023-06-06
2,3,2023-08-31 05:29:54,51818,1884.0,1,0.00,40.61,37,0,40.61,2023-08-31
3,4,2022-06-26 20:33:46,18164,1114.0,2,0.15,68.76,13,0,68.76,2022-06-26
4,5,2023-07-26 18:12:35,86915,408.0,1,0.00,14.64,4,0,14.64,2023-07-26

In [8]:
print(df_transactions_clean['refund_flag'].value_counts())

refund_flag
0    89974
1     2704
Name: count, dtype: int64

In [9]:
# Cek rentang tanggal transaksi
print(f"Transaksi dimulai dari: {df_transactions_clean['transaction_date'].min()}")
print(f"Transaksi berakhir di: {df_transactions_clean['transaction_date'].max()}")

Transaksi dimulai dari: 2021-01-01
Transaksi berakhir di: 2023-12-31

In [ ]:

# save cleand data
df_transactions_clean.to_csv(r'C:\protofolio\ecommerce_analytic\data bersih\transactions_clean.csv', index=False)
print("File sudah tersimpan!")

File sudah tersimpan!